[build]
  command = "CI=false npm run build"
  publish = "build"

[build.environment]
  CI = "false"
  NODE_VERSION = "18"
  SENDGRID_API_KEY = "your_sendgrid_api_key_here"
  FROM_EMAIL = "noreply@georgiastride.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 